export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const VIEW_EMPLOYEE = 'VIEW_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';